### ISSUE TITLE
Sandbox SPA example stuck in loop

### ISSUE THREAD

**Issue by dsws** [adobe/alloy#1005]
### Expected Behaviour
Not to be stuck in loop

### Actual Behaviour

Compiled with problems:X

ERROR

[eslint] 
src/PersonalizationSpa.js
  Line 7:3:   'usePropositions' was used before it was defined  no-use-before-define
  Line 24:3:  'usePropositions' was used before it was defined  no-use-before-define
  Line 40:3:  'usePropositions' was used before it was defined  no-use-before-define

Search for the keywords to learn more about each error.

Then it goes into some loop that makes a call to https://edge.adobedc.net/ee/va6/v1/interact... every couple of seconds.

#### Steps to Reproduce

Build the lb then run sandbox and visit http://localhost:3000/personalizationSpa/products

#### Platform and Version

  "name": "@adobe/alloy",
  "version": "2.17.0",

**Comment by stacyburris** [comment]
Seeing the same behaviour when clicking on the Products and Cart buttons

**Comment by carterworks** [comment]
Fixed.
