### ISSUE TITLE
Not able to minify Alloy JS with YUI compressor.

### ISSUE THREAD

**Issue by umangm99** [adobe/alloy#1104]
Hi Adobe Team,

We want to use websdk in our public and private site. While for public site we use Adobe Data collection to configure web sdk, for private site we place code of library directly in our servers. For doing this we have implimented YUI compressor which merge and compress all JS files.

Now YUI compressor works fine with AT.js analytics js , DIL , Visitor etc but it gives issues with Alloy JS. Please fix your Alloy JS library for compressor to understand. Thanks

**Comment by jonsnyder** [comment]
Can you give more details about what you are doing and why? It looks like YUI compressor can have problems with ES6 modules, which we use inside the Alloy library. We have a build process that already compresses the file, why don't you use that? The NPM library publishes ES6 and ES2015 modules. Have you tried the ES2015 modules? https://www.npmjs.com/package/@adobe/alloy Does it work with the "built" version of the library?

**Comment by umangm99** [comment]
Hi @jonsnyder  we have a process in our private site build where in we combine multiple libraries into 1 and compress them at time of combining if not already compressed. We use YUI compressor for this purposes and YUI should be able to read and understand JS.

I have already tried with both Alloy.js & Alloy.min.js and YUI is giving error with both of them. 

As part of build process we can't use NPM modules so it will really help if you can publish ES5 version of complied library as well. Thanks

**Comment by jonsnyder** [comment]
I ran the YUI compressor on alloy.js. Its parsing is different than most JavaScript tools I've used. It appears to tokenize these strings into keywords without regard to context:

- finally
- default
- boolean
- catch
- in

We use these as function names within the code, but YUI thinks they are keywords and complains about syntax errors. To support YUI compressor we would need to remove our use of these names. "default", "boolean", and "in" are simple enough to change, but finally and catch are a part of the Promise syntax.

**Comment by umangm99** [comment]
Hi @jonsnyder thanks for actively looking into this one, I understand that finally and catch are big issues, for now I have gone through alloy JS code line by line, looking for .finally and changed it to .["finally"] and same for catch to build successfully but this is not very maintainable for us.

I really appreciate you looking into this actively for a solution.

**Comment by jonsnyder** [comment]
Web SDK isn't going to support YUI compressor. I suggest you move to modern JavaScript tools. If you absolutely need to continue to use YUI compressor, you could create a custom build process from the Alloy NPM library https://www.npmjs.com/package/@adobe/alloy. Perhaps using rollup and babel with this babel plugin: https://github.com/sabberworm/babel-plugin-yui-compressor-fix-reserved-keywords
