### ISSUE TITLE
Feature Request: "Never Track" list or regex for external link clicks

### ISSUE THREAD

**Issue by scott2217** [adobe/alloy#1198]
This is a request for feature parity with Adobe Analytics Launch extension to be able to specify link targets that should not count as external links.  We would like to be able to specify what constitutes an external link click by providing either a list of strings or a regular expression in which, if the URL being linked to matches said string or regex, does not count as an external link click.  This feature is present in the Adobe Analytics extension for Launch, but not for Web SDK.

**Comment by carterworks** [comment]
You can filter link clicks using the `clickCollection.filterClickDetails` option on the `configure` command.

https://experienceleague.adobe.com/en/docs/experience-platform/web-sdk/commands/configure/clickcollection#click-collection-settings-using-the-web-sdk-javascript-library
