### ISSUE TITLE
DefaultConsent: Pending is sending events before consent is set

### ISSUE THREAD

**Issue by marschro-divae** [adobe/alloy#1208]
### Expected Behaviour
When setting 
```javascript
defaultConsent: "pending"
```
I expect that no event is send before an explicit  consent is given with setConsent

As soon as consent is given - i.e. with set consent in this form:
```javascript
alloy("setConsent", {
  consent: [{
    standard: "Adobe",
    version: "2.0",
    value: {
      collect: {
        val: "y"
      },
      metadata: {
        time: "YYYY-10-12T15:52:25+00:00"
      }
    }
  }]
});
```
The consent must be correctly applied and all `sendEvent` commands that are in the queue should be send.

### Actual Behaviour
When "pending" is set, the web sdk sends events event without having set the consent with `setConsent`

### Reproduce Scenario (including but not limited to)
Set it up like described in the documentation

#### Platform and Version
- Web SDK Extension: v2.27.0
- But can be reproduced in all older versions

#### Sample Code that illustrates the problem
See above

**Comment by jonsnyder** [comment]
@marschro-divae I see you closed this. Did you figure it out? Is this still an issue?

**Comment by marschro-divae** [comment]
Hi @jonsnyder - thanks for checking. Its not an issue anymore and I figured it out. 
It was an error in the testing setup. so it works as expected, but I tested it wrongly :)
