### ISSUE TITLE
Configuration command fails when Adobe Experience Cloud Debugger extension is installed (Chrome)

### ISSUE THREAD

**Issue by laurentiumagureanu** [adobe/alloy#369]
### Expected Behaviour
alloy("configure" {...}) should create and validate the configuration in order for subsequent edge calls to work

### Actual Behaviour
The configuration command fails if Adobe Experience Cloud Debugger extension is installed (tested on latest stable version of Chrome)

### Reproduce Scenario (including but not limited to)
Install Adobe Experience Cloud Debugger and test the configuration command

#### Steps to Reproduce
When the configure command is executed, this line is used to log a successful execution:
https://github.com/adobe/alloy/blob/23b8fa2cf6ffc53ae04be4d3434c731e2618ad62/src/core/buildAndValidateConfig.js#L57

`config` object is created using this function
```javascript
const createConfig = options => {
  return assign(Object.create(null), options);
};
``` 
located here:
https://github.com/adobe/alloy/blob/23b8fa2cf6ffc53ae04be4d3434c731e2618ad62/src/core/config/createConfig.js#L15

This function creates an object with no prototype.

When the Adobe Experience Cloud Debugger is active, it intercepts log messages and tries to capture the values. The arguments are passed as an array to some analytics function belonging to the extension which in turns tries to join the array together using `.join`.

This fails because objects without prototypes cannot be converted to a primitive and the return statement of the `buildAndValidateConfig` function is never reached.

#### Platform and Version
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36

Tested with alloy Alpha 8

#### Sample Code that illustrates the problem
Here is a screenshot from the Chrome debugger with the code from the extension that causes the issue
![image](https://user-images.githubusercontent.com/6639076/75248910-c607a480-57dd-11ea-9bef-e997d24b94e9.png)

#### Logs taken while reproducing problem
```
VM1048:1 Uncaught (in promise) TypeError: [alloy] Cannot convert object to primitive value
Note: Errors can be suppressed by setting the errorsEnabled configuration option to false.
    at Array.join (<anonymous>)
    at console.a.<computed> [as log] (<anonymous>:1:12359)
    at process (clientlib-base.js:15239)
    at buildAndValidateConfig (clientlib-base.js:14965)
    at configureCommand (clientlib-base.js:15736)
    at execute (clientlib-base.js:11363)
    at clientlib-base.js:11410
    at new Promise (<anonymous>)
    at executeCommandFactory (clientlib-base.js:11405)
    at instanceFactory (clientlib-base.js:8542)
```

**Comment by jfkhoury** [comment]
@laurentiumagureanu this is a known issue with the debugger; it’s been fixed but Chrome store hasn’t published the latest version yet. (Or maybe they did and you have an old version)
