### ISSUE TITLE
ListVar Support for XDM lists Adobe Analytics

### ISSUE THREAD

**Issue by dancingcactus** [adobe/alloy#446]

**Comment by dancingcactus** [comment]
AN-212134

**Comment by dancingcactus** [comment]
AN-213864

**Comment by vivasd** [comment]
ListVars are supported with the default delimiter of a comma. If you would like to change the delimiter you will need to open a ticket. Functionality to make changes without a ticket is on the roadmap.

**Comment by jfkhoury** [comment]
Please visit https://github.com/orgs/adobe/projects/18 to check on roadmap changes.
