### ISSUE TITLE
Feature Request : XDM Profile request/response from AEP Web SDK

### ISSUE THREAD

**Issue by pitchmuc** [adobe/alloy#529]
Hello, 

I would like to request a new feature, that I think would be really helpful for a lot of customers.

## Expected Behaviour
When sending the request to AEP, I would like to be able to request for the XDM Individual Profile from AEP in the response. Therefore, I would be able to use the data in the promise response. 

### Example
From the official definition: alloy("commandName", options)
It could work like : 
```
alloy("getData", {"path":[
    "_xdm.profile.products.productRecommended",
    "_xdm.profile.person.propensityScore",
   "_xdm.profile.identities.otherIdentity",
    ]
}).then((response)=>{
    s.eVarX = response["_xdm.profile.person.propensityScore"]
})
```

Or we could even combine it as option to other methods like : 
```
var myXDMData = { ... };

alloy("sendEvent", {
  "xdm": myXDMData,
  "type": "commerce.purchases",
  "getData": [
    "_xdm.profile.products.productRecommended",
    "_xdm.profile.person.propensityScore",
   "_xdm.profile.identities.otherIdentity",
    ]
});
```
##### Target: 
1. Simplify implementation of experiments
At the moment, we would need to create a different experiment in Target for each of the attributes that are returned. In that experiment, we need to copy paste the code lots of time, often hard coded. 
What we could derive from this is the ability to automate the change on the page based on the data returned (ex ; Product recommended). 

##### Analytics

1. Dynamic attributes
At the moment, it is only possible to track whatever has been given by client front or back end (from data layer). We could also be a front end provider. It will be useful for dynamic attributes as well. 

2. Enrich front-end ML 
Possibility to realize front end machine learning with more data from AEP that what is currently on page. 

#### Other

1. Enrich Third Party Tags
Possibility to use the response provided to enrich Pixels from vendors

2. Enrich Front End from clients
Clients not having AEM (so direct connect in the future with AEP) would love to have this possibility, without relying on Target (which is has its own library to load and so on). 

## Actual Behaviour

This is currently not supported. 

## Consideration

Obviously, this would require longer time to proceed so delay in the response is to be expected.

**Comment by dancingcactus** [comment]
@pitchmuc Thank you for submitting this. I agree this isn't JS related but this is a good place to submit stuff for the edge network as well. We'll take a look in our planning meeting and get back to you.

**Comment by dancingcactus** [comment]
@pitchmuc We have reviewed this. We are working on being able to write data to the profile ( #472 ). However, we did discuss this with the profile team and this would be a security/privacy issue by being able to access the profile via an unauthenticated API. I am going to mark this as closed for now, at least until we have more controls on profile to support this use-case
