### ISSUE TITLE
Feature Request: Distinguish values in fields that are set in the XDM Object data element

### ISSUE THREAD

**Issue by ericmatisoff** [adobe/alloy#570]
### Expected Behaviour
Make it very clear what values are set in an XDM Object data element.

### Actual Behaviour
It's not possible to distinguish which values are set in this data element, vs those set by Alloy automatically. (hint, it's just 1 field in the first _atag object)

![image](https://user-images.githubusercontent.com/5855401/89573724-0e010d80-d7f9-11ea-85e9-d8a265a6008e.png)

### Solution:
Perhaps similar to the change to identify values changed in schemas via AEP Mix-Ins. They've recently made it more obvious using bold lines instead of gray checkboxes:
https://jira.corp.adobe.com/browse/PLAT-58299

**Comment by jfkhoury** [comment]
Jira ticket: https://jira.corp.adobe.com/browse/CORE-50488
