### ISSUE TITLE
Feature Request: Add to Web SDK for Analytics Mixin

### ISSUE THREAD

**Issue by ericmatisoff** [adobe/alloy#571]
### Expected Behaviour
All Analytics-related fields would be included in the **Web SDK for Analytics** Mixin.

### Actual Behaviour
Commerce, product, and marketing fields are not included and need to be added separately.

### Reproduce Scenario (including but not limited to)
Add the **Web SDK for Analytics** Mixin

### Suggestion
![image](https://user-images.githubusercontent.com/5855401/89790344-ca0b5280-daef-11ea-9113-02c63f7b2f27.png)
Suggestion is to include the fields from the:

1. commerce
2. marketing
3. productListItems

Instead of having to manually add the **ExperienceEvent details for marketing** and **ExperienceEvent commerce details** Mixins.

**Comment by dancingcactus** [comment]
@ericmatisoff This isn't something we have a desire to do as it violates the compose-ability principles of XDM. What might make more sense would be to create a set of mix-ins based on different verticals (e.g. Retail, Fin-Serve, High Tech) and such to model the data for them then we can adapt how Analytics ingests those types of data.

**Comment by ericmatisoff** [comment]
@dancingcactus - gotcha, thanks Justin. I guess the confusion is the Mix-in is called "Web SDK for Analytics" but it doesn't support all the fields that are listed in the "Automatically Mapped to Analytics" variables. Regardless of vertical (retail, fsi, etc), they'll still be sending data to s.products (for example) in Adobe Analytics, and the only way to do that is with productListItems.

**Comment by dancingcactus** [comment]
@ericmatisoff. I totally missed that you were using the Web SDK for Analytics mix-in. I'll re-open.

**Comment by dancingcactus** [comment]
@ericmatisoff We took a look at this and it appears that this is a custom mixin that is specific to your org. So you should be able to just add commerce to the mixin.

**Comment by ericmatisoff** [comment]
Looks like I mentioned the wrong one:
https://experience.adobe.com/#/@amcevangelists/platform/schema/browse/https%3A%2F%2Fns.adobe.com%2Fexperience%2Faep-web-sdk-experienceevent

**AEP Web SDK ExperienceEvent Mixin** I guess is what I should have been referencing. I see in the description that it's focused on the automatically collected variables, but IMO it should include all automatically mapped variables. Will be a significant improvement to the schema creation process for customers.

**Comment by ericmatisoff** [comment]
PS - can't believe I thought the Web SDK for Analytics Mixin was a built-in Mixin. I built it!

**Comment by dancingcactus** [comment]
Got it. Thanks for the clarification. We are actually going after having a lot of mix-ins with built in mappings (e.g. Internal search, product finding methods). I am not sure it makes sense to bundle all of these with the AEP Web SDK mixin. However, we are thinking about having Industry/Vertical mix-ins that will solve a lot of this need.
