### ISSUE TITLE
ProductListRemovals doesn't map to Remove Cart in Adobe Analytics (scRemove)

### ISSUE THREAD

**Issue by ericmatisoff** [adobe/alloy#578]
### Expected Behaviour
**commerce.productListRemovals.value = 1** maps to the **Cart Removals** metric in Adobe Analytics.

### Actual Behaviour
Cart Removals is not populated with data.

### Reproduce Scenario (including but not limited to)
![image](https://user-images.githubusercontent.com/5855401/90528833-11718e80-e141-11ea-8567-2a168e3b3f4a.png)

![image](https://user-images.githubusercontent.com/5855401/90528879-1d5d5080-e141-11ea-9548-8e616e95fe60.png)

**Comment by dancingcactus** [comment]
@ericmatisoff Could you past the JSON payload you are sending here. That will help us diagnose the problem.

**Comment by ericmatisoff** [comment]
`{"events":[{"xdm":{"web":{"webPageDetails":{"URL":"https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/#"},"webReferrer":{"URL":"https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/"}},"device":{"screenHeight":1050,"screenWidth":1680,"screenOrientation":"landscape"},"environment":{"type":"browser","browserDetails":{"viewportWidth":987,"viewportHeight":948}},"placeContext":{"localTime":"2020-08-18T11:18:54.840-04:00","localTimezoneOffset":240},"timestamp":"2020-08-18T15:18:54.840Z","implementationDetails":{"name":"https://ns.adobe.com/experience/alloy","version":"2.1.0","environment":"browser"},"commerce":{"productListRemovals":{"value":1}},"productListItems":[{"SKU":"24-mb02","name":"fusion backpack"}]}}],"query":{"identity":{"fetch":["ECID"]}},"meta":{"state":{"domain":"ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud","cookiesEnabled":true,"entries":[{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_consent","value":"general=in"},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_identity","value":"CiY2MTI5MTY1OTM4NDk0ODY0MDgyMDEyNzkxODYzMTE5MzQ2Mzc2N1INCMHJ4uu-LhAAGAEgCKABwcni674uqAGfrN2025PV_ukB8AGc16mQwC4="},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_consent_check","value":"1"},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_personalization_sessionId","value":"cfbe3d2f-e755-4225-a46e-ace4f8301731"}]}}}
`

**Comment by dancingcactus** [comment]
Referenced in AN-230356

**Comment by dancingcactus** [comment]
@ericmatisoff We weren't able to reproduce this. 

```javascript
{"events":[{"xdm":{"web":{"webPageDetails":{"URL":"https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/#"},"webReferrer":{"URL":"https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/"}},"device":{"screenHeight":1050,"screenWidth":1680,"screenOrientation":"landscape"},"environment":{"type":"browser","browserDetails":{"viewportWidth":987,"viewportHeight":948}},"placeContext":{"localTime":"2020-08-18T11:18:54.840-04:00","localTimezoneOffset":240},"timestamp":"2020-08-18T15:18:54.840Z","implementationDetails":{"name":"https://ns.adobe.com/experience/alloy","version":"2.1.0","environment":"browser"},"commerce":{"productListRemovals":{"value":1}},"productListItems":[{"SKU":"24-mb02","name":"fusion backpack"}]}}],"query":{"identity":{"fetch":["ECID"]}},"meta":{"state":{"domain":"ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud","cookiesEnabled":true,"entries":[{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_consent","value":"general=in"},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_identity","value":"CiY2MTI5MTY1OTM4NDk0ODY0MDgyMDEyNzkxODYzMTE5MzQ2Mzc2N1INCMHJ4uu-LhAAGAEgCKABwcni674uqAGfrN2025PV_ukB8AGc16mQwC4="},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_consent_check","value":"1"},{"key":"kndctr_EDA8E66E593730510A495EFA_AdobeOrg_personalization_sessionId","value":"cfbe3d2f-e755-4225-a46e-ace4f8301731"}]}}} 
```
Here is what got mapped
```javacsript
{
  "bh": "948",
  "bw": "987",
  "c.a.x.device.screenorientation": "landscape",
  "c.a.x.environment.type": "browser",
  "c.a.x.placecontext.localtime": "2020-08-18T11:18:54.840-04:00",
  "c.a.x.placecontext.localtimezoneoffset": "240",
  "c.a.x.productlistitems.[0].sku": "24-mb02",
  "c.a.x.timestamp": "2020-08-18T15:18:54.840Z",
  "cust_hit_time_gmt": "1579781427",
  "events": "scRemove",
  "g": "https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/#",
  "pl": ";fusion backpack",
  "r": "https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/",
  "s": "1680x1050"
} 
```

Is this still not working for you?

**Comment by ericmatisoff** [comment]
Unfortunately, yes, still not seeing any Cart Removals. I'd expect the above mapping to fire one too 
![image](https://user-images.githubusercontent.com/5855401/91200126-c15c7400-e6cc-11ea-8ae3-cc08de2c3482.png)

**Comment by ericmatisoff** [comment]
Checking in today and still not seeing Cart Removals. Really strange!

**Comment by dancingcactus** [comment]
Do you have a page we could look at?

**Comment by ericmatisoff** [comment]
Yes absolutely, sorry I missed that.
https://ericm-uzr7nty-3bng3vp43k57a.demo.magentosite.cloud/
Add any product to cart, click the minicart in the top-right, then click the trashcan in the minicart to remove the product (and fire the associated tag).

Thanks for looking into this

**Comment by jfkhoury** [comment]
@ericmatisoff Is this still an issue?

**Comment by ericmatisoff** [comment]
I just gave it a try to see if any Cart Removals appear in AA. Will check later to confirm

**Comment by ericmatisoff** [comment]
No longer an issue. Going to close
