### ISSUE TITLE
Feature Request: Support for region ID / location hint lookup

### ISSUE THREAD

**Issue by hitGovernor** [adobe/alloy#579]
This request is for a method to return the region ID via the AEP WebSDK / alloy.js API (similar to getLocationHint()).

Background:
The scenario I was thinking about was one where the existing visitorapi.min.js library is currently being used to retrieve the ECID + imsregion. That information is passed to a third-party server-side solution that sends data to Adobe Analytics. From there, SSF is leveraged to send the data on to AAM.

We’re evaluating the possibility of replacing visitorapi.min.js with AEP websdk to take advantage of performance improvements, but keeping the third-party server-side solution to get the bulk of the data to AA. In this scenario, we want to continue leveraging the SSF setup between AA and AAM.

In both solutions, AppMeasurement is not on the page. We’re trying to avoid adding DIL.js (which we may need in the current setup as a way to retrieve audience/segment IDs and cookies), and we understand that AEP websdk should help with this. (It’s all about speed and performance!)

If we can’t get the imsregion back using AEP websdk, then we either can’t use AEP websdk, or we have to look at restructuring our configuration, and I’m not sure there’s much appetite for that at this point in time. (My assumption here is that we’d set up the edge configuration to send data to AAM and not AA, letting the existing third-party server-side setup do it’s thing. We’d disable SSF for the related report suites in the process. This also adds complexity to the structure of the payload going to the Edge/AAM so that it matches up with what’s going through the third-party today.)

**Comment by jfkhoury** [comment]
@hitGovernor 

Hey Brian, I wanted to give you some updates on this issue:

The Edge team has released a change to return the AAM Region ID in a header on every response.

The next step is to release a change in Alloy to return this ID in the `sendEvent` command (Or a separate command ). We are in the process of finalizing the design. I will keep you posted on the timing.


**I have one other question though:**

If you are planning on using Alloy, why not leveraging it to send the data to AA & AAM directly using the same hit, which will simplify your implementation significantly? You can even leverage Launch Server Side Forwarding and send that same hit to whatever other Analytics/Data lake systems you might have. The client would become much simpler. 

The answer might be related to timing and resources needed to restructure, which I 100% understand; I just wanted to double check.

Thank you.
Joe

**Comment by hitGovernor** [comment]
Thanks for the update, Joe!

I'm all for grouping everything under Adobe's architecture, but this
request is for a client who will be (is) using a third-party service that
makes a migration to a full-blown Alloy + Launch Server Side setup a
non-starter. In fact, this whole conversation started as the client was
getting the migration underway for that other third-party service.

Knowing that we'll have access to the region ID via Alloy's sendEvent
response is great news, though! Thanks for sticking with it!

~ b

**Comment by vivasd** [comment]
This was released in version 2.4.0 of the Web SDK.
https://experienceleague.adobe.com/docs/experience-platform/edge/identity/overview.html?lang=en#retrieving-the-visitor-id-and-region-id
