### ISSUE TITLE
Switch Sandbox Dropdown disabled - Web SDK Extn 2.1.0

### ISSUE THREAD

**Issue by anilytics** [adobe/alloy#580]
### Expected Behaviour
Ability to switch sandbox in Data element create UI

### Actual Behaviour
The dropdown to change sandbox is disabled and does not provide a way to switch to newly created dev sandbox in AEP. 

![aep_sandbox_alloy](https://user-images.githubusercontent.com/33175148/90837727-3d398200-e396-11ea-94b5-ef3f87e2e806.png)
#### Steps to Reproduce
As a pre requisite have a schema created in prod instance 
P.S: we had to do this since we had no access to sandbox earlier

1.) Create multiple sandboxes within AEP
2.) Configure new edge env to point to new sandbox and Schema
3.) Update AEP extension in launch to point to new edge conig
4.) Navigate to create data element with Web SDK
5.) UI shows "production sandbox" with dropdown disabled 

*attached screenshot
*Please reach out to me if you need org information

#### Platform and Version
AEP Web SDK Adobe ⋅ v2.1.0

**Comment by dancingcactus** [comment]
@anilytics A new version of the Launch Extension that fixes this issue is available today.

**Comment by anilytics** [comment]
thank you! this works as expected now.
