### ISSUE TITLE
Bug: A4T data is not getting shared to Analytics

### ISSUE THREAD

**Issue by ericmatisoff** [adobe/alloy#586]
### Expected Behaviour
Target activity data to appear in the associated report suite that was selected in each Target activity.

### Actual Behaviour
Analytics is not receiving any data from Target.

### Reproduce Scenario (including but not limited to)
Adobe Org: Adobe Marketing Cloud Evangelists
Target Client Code: adobemarketingcloude
Report Suites: Analytics Challenge, Pre-0 Luma

#### Steps to Reproduce
![image](https://user-images.githubusercontent.com/5855401/91497341-db908080-e88b-11ea-9201-e3fefe74a3a4.png)
https://sc5.omniture.com/x/5_bvepn

**Comment by jfkhoury** [comment]
@ericmatisoff Any chance you can provide an Edge Trace for Analytics?

**Comment by ericmatisoff** [comment]
yessir: 
![image](https://user-images.githubusercontent.com/5855401/91875202-2bcf6000-ec49-11ea-841b-55a1d08f2379.png)

**Comment by ericmatisoff** [comment]
Just had a thought:
I'm using Processing Rules to set the Customer Perspective of these hits to Background. (this is necessary because I'm making one call at the top of the page for Target personalization, and another at window load where the Perspective is set to Foreground and the data layer/DOM can be read.) Background Customer Perspectives will filter calls out of the report suite so we don't have two tags firing on each page.

Perhaps the A4T hit is being bucketed as Background and that's why it's not making it into the report suite?

**Comment by ericmatisoff** [comment]
(I'm testing this theory out now, fyi)

**Comment by dancingcactus** [comment]
In conversation with @ericmatisoff we discovered that was indeed the problem.
