### ISSUE TITLE
Allow customers to set mbox 3rd party IDs

### ISSUE THREAD

**Issue by vivasd** [adobe/alloy#605]

**Comment by jfkhoury** [comment]
TODO: Work with Mitch Rice & David Son on this.

**Comment by jfkhoury** [comment]
**Next steps**:

- Test mbox3rdpartyid: https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=Target&title=Alloy+vs+at.js+feature+gap (@Mr-Ice-Adobe)

- Document this feature in the Alloy docs

**Comment by patrickhegnauer** [comment]
is this somewhere documented how to do this via web sdk?

**Comment by vivasd** [comment]
We added it here now, thanks for finding that gap :) 
https://experienceleague.adobe.com/docs/experience-platform/edge/personalization/adobe-target/using-mbox-3rdpartyid.html?lang=en
