### ISSUE TITLE
Feature Request:   Data Elements ❤️ Schemas In Launch Server Side

### ISSUE THREAD

**Issue by RudiShumpert** [adobe/alloy#624]
### Expected Behaviour
Allow Data Elements within Launch SSF to map directly to the Schema Elements using the visual display.

Bonus idea:  Provide a step when the user can load up a schmea and select a set of elements to have data elements created for them.
![Screen Shot 2020-10-28 at 11 38 08 AM](https://user-images.githubusercontent.com/37945125/97459612-54569c00-1912-11eb-8077-fbd2821faa1c.png)

**Comment by jfkhoury** [comment]
@RudiShumpert Here are the JIRA tickets that are tracking this effort:

https://jira.corp.adobe.com/browse/CORE-54152
https://jira.corp.adobe.com/browse/CORE-54153
https://jira.corp.adobe.com/browse/CORE-54154
