### ISSUE TITLE
Feature Requests:  Rules ❤️ Schemas In Launch Server Side

### ISSUE THREAD

**Issue by RudiShumpert** [adobe/alloy#625]
### Expected Behaviour
Within Launch SSF:  allow users to reference schema elements directly as they do now with Data Elements.

![Screen Shot 2020-10-28 at 11 41 04 AM](https://user-images.githubusercontent.com/37945125/97459861-98e23780-1912-11eb-83a7-51775f70a0e7.png)

**Comment by jfkhoury** [comment]
@RudiShumpert Here are the JIRA tickets that are tracking this effort:

https://jira.corp.adobe.com/browse/CORE-54152
https://jira.corp.adobe.com/browse/CORE-54153
https://jira.corp.adobe.com/browse/CORE-54154
