### ISSUE TITLE
Adobe Target Property ID Dynamic Value

### ISSUE THREAD

**Issue by joseajimenezjr** [adobe/alloy#641]
### Expected Behaviour
I expect to be able to pass the  property ID from the client side. 

### Actual Behaviour
Currently I have to set it up on the edge configuration which is then referenced at the extension level. This means I have to create a separate Launch Property for each property in Target which could be alot easier if I can pass through the XDM model a value with the Target property value. 

#### Steps to Reproduce
N/A

#### Platform and Version
Launch, Web SDK 2.3.0

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by jonsnyder** [comment]
One solution you could use right now is to dynamically set the edge configuration id in the Launch Property. So you would setup an edge configuration for each target property. Then in Launch use a data element to setup the edge configuration id. This would enable you to use the same Launch property for multiple edge configurations.

**Comment by jfkhoury** [comment]
We will reject this issue and wait for more similar requests before we revisit it.
