### ISSUE TITLE
Add a feature similar to s.abort to Alloy

### ISSUE THREAD

**Issue by vivasd** [adobe/alloy#654]
As a customer using the AEP Web SDK I want to have the ability to stop all event from firing, similar to the s.abort feature in AppMeasurement, so that if a bot is detected browsing my page I can stop these hits from firing.

**Comment by dancingcactus** [comment]
This is now complete. See [Release Notes](https://experienceleague.adobe.com/docs/experience-platform/edge/release-notes.html) for version 2.4.0
