### ISSUE TITLE
Logging is on by default

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/alloy#68]
### Expected Behaviour
When calling configure without an explicit {... "log" : true ...} I would expect no logging, but I get it anyway.

//without logging
alloy("configure", {
    "propertyID": "sdi-orbital",
    "collectionUrl": ""
  })
  .then(function(value) {
    console.log("alloy configure success", value);
  })
  .catch(function(error) {
    console.log("alloy configure error", error);
  })

//////////////////////////////////////////////////////
// Result
//////////////////////////////////////////////////////
  [alloy] Runtime configuration:
   {
    "propertyID": "sdi-orbital",
    "collectionUrl": "",
    "edgeDomain": "edgegateway.azurewebsites.net",
    "shouldStoreCollectedData": 1,
    "device": "Chrome-Mac",
    "idSyncsEnabled": true,
    "destinationsEnabled": true,
    "context": [
      "web",
      "device",
      "environment",
      "placeContext"
    ]
  }
  airbrake.min.js:2 alloy configure success undefined
  Promise {<resolved>: undefined}
  //////////////////////////////////////////////////////

  
  //with logging
  alloy("configure", {
      "propertyID": "sdi-orbital",
      "collectionUrl": "",
      "log": true
    })
    .then(function(value) {
      console.log("alloy configure success", value);
    })
    .catch(function(error) {
      console.log("alloy configure error", error);
    })
    
//////////////////////////////////////////////////////
// Result - Pretty much the same as above but this one has the `log:true` setting
//////////////////////////////////////////////////////
[alloy] Runtime configuration:
 {
  "propertyID": "sdi-orbital",
  "collectionUrl": "",
  "log": true,
  "edgeDomain": "edgegateway.azurewebsites.net",
  "shouldStoreCollectedData": 1,
  "device": "Chrome-Mac",
  "idSyncsEnabled": true,
  "destinationsEnabled": true,
  "context": [
    "web",
    "device",
    "environment",
    "placeContext"
  ]
}
airbrake.min.js:2 alloy configure success undefined
Promise {<resolved>: undefined}
//////////////////////////////////////////////////////

//with logging explicitly off
alloy("configure", {
    "propertyID": "sdi-orbital",
    "collectionUrl": "",
    "log": false
  })
  .then(function(value) {
    console.log("alloy configure success", value);
  })
  .catch(function(error) {
    console.log("alloy configure error", error);
  })
  
//////////////////////////////////////////////////////
// Result - No logging
//////////////////////////////////////////////////////
Promise {<pending>}
VM2334:8 alloy configure success undefined

**Comment by jfkhoury** [comment]
Hi @stewartschillingsdi,

When you set the `log` config or call the `alloy("log"...)` command to `true` or `false`, the value gets set in local storage by default.

So to undo that initial setting, you need to set the `log` to the opposite value.

So if you try:

```
alloy("configure", {
    "propertyID": "sdi-orbital",
    "log": false
});
```
You should stop seeing logs in the console.

I think this should be clarified in the docs, thank you for bringing it up.

**Comment by Aaronius** [comment]
@stewartschillingsdi, I'm curious to know how you think this should work. [In the docs](https://launch.gitbook.io/adobe-experience-platform-web-sdk/fundamentals/logging), we outline three different ways to toggle logging: (1) configuration, (2) running the `log` command and (3) passing a querystring parameter.

For each of these ways of toggling logging, how long would you expect the state of logging be persisted?

**Comment by stewartschillingsdi** [comment]
@Aaronius  - I lost the link to the docs...  I was going by the info given in Assignment#3.  The docs are clear on this (and 3 options is more than enough).  ;)

@jfkhoury  - Given that, it there any reason for `log` be included in the configure log message?
