### ISSUE TITLE
When sending multilple events in succession, alloy only seems to send the first.

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/alloy#69]
### Expected Behaviour
All events sent via `alloy("event",{...})` get sent. 

### Actual Behaviour
Only first event is sent - OR - maybe only the 1st is logged? 

### Reproduce Scenario (including but not limited to)
After configuration call, make several event calls.  Watch logs. 

#### Platform and Version
Alloy alpha.3 - MacOS Chrome 
#### Logs taken while reproducing problem

VM3306:8 alloy configure success undefined
VM3306:27 In edgeAlphaEventBridge(alloy). Sending : Product Viewed {type: "Product Viewed", data: {…}}
VM3306:27 In edgeAlphaEventBridge(alloy). Sending : User Detected {type: "User Detected", data: {…}}
VM3306:27 In edgeAlphaEventBridge(alloy). Sending : Page Loaded {type: "Page Loaded", data: {…}}
alloy.js:2258 [alloy] Sending network request (response will be ignored): {events: Array(1), meta: {…}}
VM3306:32

**Comment by jfkhoury** [comment]
@stewartschillingsdi 

Can you please attach the code snippet?

I tried reproducing the same behavior using the Alpha 3 build, but I'm seeing all the events in the console:

```
[alloy] Runtime configuration:
 {
  "propertyID": 9999999,
  "log": true,
  "edgeDomain": "edgegateway.azurewebsites.net",
  "shouldStoreCollectedData": 1,
  "device": "Chrome-Mac",
  "idSyncsEnabled": true,
  "destinationsEnabled": true,
  "context": [
    "web",
    "device",
    "environment",
    "placeContext"
  ]
}

alloy.js:2258 [alloy] Sending network request: {events: Array(1), meta: {…}, identityMap: {…}}
alloy.js:2258 [alloy] Sending network request (response will be ignored): {events: Array(1), meta: {…}, identityMap: {…}}
alloy.js:2258 [alloy] Sending network request (response will be ignored): {events: Array(1), meta: {…}, identityMap: {…}}

alloy.js:2258 [alloy] Received network response: {handle: Array(3), requestId: "764207dc-f225-49a1-aee4-38aab3694951"}
```

Here's my code:

```javascript
      alloy("configure", {
        propertyID: 9999999,
        log: true
      });

      alloy("event", {
        // NOTE: `viewStart` is a special type of events.
        // View docs for more info.
        type: "viewStart",
        data: {
          "xdm:URL": [location.href],
          "xdm:name": [location.pathname.substring(1) || "home"]
        }
      }).then(function(data) {
        console.log("Sandbox: View start event has completed.", data);
      });

      alloy("event", {
        type: "random event 1",
        data: {
          name: "Joe"
        }
      });

      alloy("event", {
        type: "random event 2",
        data: {
          lastname: "khoury"
        }
      });
```

**Comment by stewartschillingsdi** [comment]
SO... My code snippet is going to need a little explaining.  I'm running on a site that has Launch, has an event based data layer (window.appEventData), and is using the Data Layer Manager Launch Extension.    I am setting up listeners to catch each event as it is pushed onto the Data Layer.  In the event handler, I reshape the event payload and send it on to Platform Edge via an alloy("event", {}...}) call. 


```
alloy("configure", {
    "propertyID": "sdi-orbital",
    "collectionUrl": "",
    "log": true
  })
  .then(function(value) {
    console.log("alloy configure success", value);
  })
  .catch(function(error) {
    console.log("alloy configure error", error);
  })

function edgeAlphaEventBridge(dlmEvent) {
  //console.debug("Edge Alpha(alloy) : Bridge Event - dlmEvent", dlmEvent);
  var dlmEventCopy = JSON.parse(JSON.stringify(dlmEvent.detail))
  //console.debug("Edge Alpha(alloy) : Bridge Event - dlmEventCopy", dlmEventCopy);

  delete dlmEventCopy.event;
  delete dlmEventCopy.__meta;

  var alloyPayload = {
    "type": dlmEvent.detail.event,
    "data": dlmEventCopy
  }

  console.debug("In edgeAlphaEventBridge(alloy). Sending :", dlmEvent.detail.event, alloyPayload);

  alloy("event", alloyPayload)
  .then(function(_res) {
    var requestBody = _res.requestBody
    var responseBody = _res.responseBody;
    console.debug("(alloy) requestBody, responseBody",requestBody, responseBody);
  })
  .catch(function(error) {
    console.log("alloy error", error);
  });

}

_satellite._container.extensions["data-layer-manager-search-discovery"].settings.eventNames
  .forEach(function(evt) {
    var subscribedEvent = ["SDI-DLM", evt.eventName].join(":");
    window.removeEventListener(subscribedEvent, edgeAlphaEventBridge, false);
    window.addEventListener(subscribedEvent, edgeAlphaEventBridge, false);
    console.debug("Edge Alpha(alloy) : Listener added for " + subscribedEvent);

  })

```

You can see this on https://orbitalprovisions.searchdiscovery.com/ . ( use password - "astp" )

**Comment by stewartschillingsdi** [comment]
Enable Verbose logging and filter on "alloy"

![Screen Shot 2019-06-19 at 3 56 09 PM](https://user-images.githubusercontent.com/22940746/59799888-eeccb700-92aa-11e9-892a-6d35664f037b.png)

**Comment by Aaronius** [comment]
Thanks for this @stewartschillingsdi. If you can keep that site available in its current state for the next couple hours, that would be helpful. I'm going to start debugging this right now

**Comment by Aaronius** [comment]
@stewartschillingsdi, here's what happening. Before the first request goes out, we check to see if we already have an ECID stored in local storage. If we don't, we let the first request go out, but we queue up subsequent requests until we received an ECID back in the response from the first request. In your case, though, neither of your requests had a `type` value of `viewStart`. Therefore, we hit an endpoint that intentionally does not send a response. Because there was not ECID in the response, the subsequent requests remained queued up inside Alloy and never sent.

I believe the solution in your case is that your first `event` command needs to have a `type` value of `viewStart`.

We need to discuss internally as a team whether what you've currently done in your page is something we want to support and how to want to handle it more appropriately.

Thanks for bringing this to our attention.

**Comment by Aaronius** [comment]
BTW, you can do what you need to do with your demo site now. Thanks for letting me use it!

**Comment by stewartschillingsdi** [comment]
You bet.  I'm glad it was helpful

**Comment by stewartschillingsdi** [comment]
That looks better
![Screen Shot 2019-06-19 at 4 54 25 PM](https://user-images.githubusercontent.com/22940746/59804058-f3956900-92b2-11e9-8859-2f5d3a9a034b.png)
