### ISSUE TITLE
Debug mode enabled by default

### ISSUE THREAD

**Issue by arobsco** [adobe/alloy#716]
### Expected Behaviour
Debug mode is only enabled using the _satellite.setDebug(true) command

### Actual Behaviour
Debug mode is always enabled by default calling _satellite.setDebug(false) will stop it but refreshing the page causes it to be enabled again

#### Steps to Reproduce
Load page with AEP installed,  debug is enabled, call _satellite.setDebug(false) and debug statements will stop
Reload page and debug will be enabled again

Additionally deleting the localStorage key has no impact and is just set again when the page is reloaded

#### Platform and Version
AEP Extension 2.4.0

#### Sample Code that illustrates the problem
Can't find the code which is causing it

#### Logs taken while reproducing problem
NA

**Comment by jfkhoury** [comment]
Thank you for bringing this up @arobsco. We will look into it.

**Comment by arobsco** [comment]
Just for context, it doesn't seem to happen in production but happens on dev and staging environments. Normally we would have this on to work on launch however it's causing a lot of additional noise for other developers who don't work on AEP

**Comment by Aaronius** [comment]
@robsco, I'm unable to reproduce this issue. It's a little odd that you're seeing it on a dev and staging Launch environment but not a production environment, since I don't believe we do anything different between environments as far as enabling logging goes. Do you have a public page where we can see this happening?

**Comment by Aaronius** [comment]
Also, could you share which operating system and browser you're using?

**Comment by robsco** [comment]
You've tagged me by accident, you want @arobsco

**Comment by arobsco** [comment]
Thanks for checking @Aaronius. I don't have anything public at the moment but let me see if I can set something up for you. I might need to DM you it on Launch Dev Slack if that's ok?

I use Windows 10 and Latest Edge and/or Chrome.

**Comment by Aaronius** [comment]
Sorry @robsco! Yes @arobsco, that will work.

**Comment by arobsco** [comment]
Found the issue, someone is calling setDebug within the application itself 🤦🏻‍♂️ Apologies! 😄

**Comment by Aaronius** [comment]
No problem. That's good news for us. Thanks for responding!
