### ISSUE TITLE
Bug: Fields saved in XDM object after someone exits the editor

### ISSUE THREAD

**Issue by vivasd** [adobe/alloy#740]

**Comment by vivasd** [comment]
To reproduce:
1. Create a new XDM Object Data Element.
2. adding necessary variables (e.g. pagename)
3. Click Save to library
4. Error appears
5. Exit XDM object editor without saving
6. Re-enter and see the field was still saved

**Comment by vivasd** [comment]
https://jira.corp.adobe.com/browse/PDCL-6371

**Comment by vivasd** [comment]
Fixed in Alloy 2.5.0

**Comment by jonsnyder** [comment]
This was actually fixed in an updated Launch version.
