### ISSUE TITLE
Event merge does not work as expected

### ISSUE THREAD

**Issue by anilytics** [adobe/alloy#768]
### Expected Behaviour
For the purchase page step, i sent three different request consisting of 
1.) custom fields
2.) Product ListItems
3.) Commerce events and purchase id

In CJA on runtime the events with same eventmergeID will be merged and this should enable breakdown of dimensions sent via different events

### Actual Behaviour
I was able to send three different events with same merge id and was ingested in dataset. I was able to see three different rows in dataset with same mergeID(attached image) 
I could only see the data for all event in the reports in CJA but unable to break them down by each other, assuming the merging all the events into one would enable this. 
In addition the same behavior was observed in adobe analytics reports. This was on assumption that the merged event in AEP would be sent as as single event to AA for processing. 

![mergeids](https://user-images.githubusercontent.com/33175148/132076126-cdc4a734-8350-43e6-bd6e-e2e5e82b3a87.jpg)

#### Steps to Reproduce
Send 3 events for same page using same mergeID
Ensure they are valid and available in dataset
Breakdown one dimension to another to test event are merged
#### Sample Code that illustrates the problem
```
eventMergeIdPromise.then(function(evtMrgId) {
    alloy("sendEvent", {
        "xdm": {
            ..event1Details
        },
        "mergeId": evtMrgId.eventMergeId
    })
})
```

**Comment by jfkhoury** [comment]
@anilytics thank you for logging this issue. Unfortunately, support for event merge ID hasn’t been implemented yet.

**Comment by anilytics** [comment]
Thank you @jfkhoury. Is this planned for future releases? 
Also to understand the concept of mergeID, will this feature merge events and make it available ONLY in AEP or will the merged event be sent to AA to be processed (as single event) 

Thanks a bunch!!

**Comment by arobsco** [comment]
Is event merge on the roadmap yet?
