### ISSUE TITLE
Update the docs link in the readme

### ISSUE THREAD

**Issue by yrodrigez** [adobe/alloy#808]
### Expected Behaviour
Redirect to the documentation

### Actual Behaviour
Error 404: Page not found

**Comment by jfkhoury** [comment]
Thank you @yrodrigez !

**Comment by carterworks** [comment]
It looks like there was some change at developer.adobe.com that broke our documentation links. `https://developer.adobe.com/apis/experienceplatform` now either 404's or redirects to `https://developer.adobe.com/experience-platform-apis`, but that only covers endpoints and doesn't have any Web SDK documentation. 

I've found 4 total links in our code that need fixing. I don't know where the _should_ go, but probably to the documentation that's on Experience League.

- [ ] [The README link to the documentation](https://github.com/adobe/alloy/blob/b11decc00b7687b573a83e4556a81c1fc4749f61/README.md?plain=1#L7): `https://adobe.ly/36dGGp6` → `https://developer.adobe.com/apis/experienceplatform/home/services/web-sdk.html`
- [ ] [`COMMAND_DOC_URI` in `validateCommandOptions.js`](https://github.com/adobe/alloy/blob/ecf056ae6aab6e61831f23ecbd8f8cc669f893a2/src/core/validateCommandOptions.js#L13): `https://adobe.ly/2UH0qO7` → `https://developer.adobe.com/apis/experienceplatform/home/services/web-sdk.html#!api-specification/markdown/narrative/edge/fundamentals/executing-commands.md`
- [ ] [The `documentationLink` for the `sendEvent` command in the `DataCollection` module](https://github.com/adobe/alloy/blob/d6f4cff7b8f23f4a173113e3d93c3648c63fa021/src/components/DataCollector/index.js#L19): `https://adobe.ly/2r0uUjh` → `https://developer.adobe.com/apis/experienceplatform/home/services/web-sdk.html#!api-specification/markdown/narrative/edge/fundamentals/tracking-events.md`
- [ ] [`COMMAND_DOC_URI` in `buildAndValidateConfig.js`](https://github.com/adobe/alloy/blob/ecf056ae6aab6e61831f23ecbd8f8cc669f893a2/src/core/buildAndValidateConfig.js#L15): `https://adobe.ly/2M4ErNE` → `https://developer.adobe.com/apis/experienceplatform/home/services/web-sdk.html#!api-specification/markdown/narrative/edge/fundamentals/configuring-the-sdk.md`

**Comment by carterworks** [comment]
#813
