### ISSUE TITLE
Sandbox not working, missing dependencies 

### ISSUE THREAD

**Issue by dsws** [adobe/alloy#999]
### Expected Behaviour

Sandbox to run

### Actual Behaviour

[eslint] Failed to load config "airbnb-base" to extend from.
Referenced from: /Users/dshulman/WebstormProjects/alloy/.eslintrc.js
ERROR in [eslint] Failed to load config "airbnb-base" to extend from.
Referenced from: /Users/dshulman/WebstormProjects/alloy/.eslintrc.js

webpack compiled with 1 error

### Reproduce Scenario (including but not limited to)

npm i
npm run start

### Solution

npm install eslint-config-airbnb-base eslint-plugin-import --save-dev

**Comment by carterworks** [comment]
Not an issue. `eslint-config-airbnb-base` and `eslint-plugin-import` are required as dev dependencies in the tor  `package.json`. If you want to run the sandbox, just run `npm install` from the root directory. You can even run `npm run dev` from the root and it will compile alloy and run the sandbox.
